# Generated by Django 5.2 on 2025-04-07 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='location_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('geocode', 'Geocode from Address'), ('first_checkin', 'Derive from First Intern Check-in')], default='first_checkin', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='geofence_radius',
            field=models.PositiveIntegerField(default=100, help_text='Radius in meters'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
