# Generated by Django 5.2 on 2025-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_organization_location_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='location_source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('geocode', 'Geocode from Address'), ('first_checkin', 'Derive from First Intern Check-in'), ('pending', 'Pending Automatic Detection')], default='pending', max_length=20),
        ),
    ]
